services:
  user:
    image: aibomgen_user
    build:
      context: .  # The API container must see the full project
      dockerfile: src/user/Dockerfile
    container_name: user-api
    ports:
      - "8000:8000"
    volumes:
      - ./src/user:/app
      - ./src/dataset/imdb:/dataset/imdb
      - ./src/trainer:/trainer  # API container sees the trainer directory
      - /var/run/docker.sock:/var/run/docker.sock  # Allow API to control Docker
    environment:
      - DATASET_PATH=/dataset
    restart: always
    networks:
      - aibomgen_network

networks:
  aibomgen_network:
    driver: bridge