services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    env_file:
      - .env
    networks:
      - internal_network
      
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    networks:
      - internal_network

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - internal_network

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    deploy:
      replicas: 3  # Define 3 replicas for the worker to demonstrate scalability
      resources:
        limits:
          memory: 4g  # Increase memory limit to 4GB
          cpus: "2.0"  # Allow up to 2 CPU cores
        reservations:
          memory: 2g  # Reserve 2GB of memory
          cpus: "1.0"  # Reserve 1 CPU core
          devices:
            - capabilities: [gpu]
    runtime: nvidia  # Ensure this is present
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - internal_network

  flower:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: flower
    entrypoint: []  # Override the entrypoint to disable entrypoint.sh (otherwise flower will run as a worker)
    command: celery -A celery_config flower --port=5555 --basic_auth=$FLOWER_BASIC_AUTH
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - worker
    env_file:
      - .env
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
