services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=EfeNgErMAnDIon  # Set a password for Redis
    command: [ "redis-server", "--requirepass", "EfeNgErMAnDIon" ]  # Secure Redis with password

  api:
    build:
      context: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://:EfeNgErMAnDIon@redis:6379/0  # Update Redis URL with password
      - CELERY_RESULT_BACKEND=redis://:EfeNgErMAnDIon@redis:6379/0

  worker:
    build:
      context: ./worker
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    mem_limit: 4g
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://:EfeNgErMAnDIon@redis:6379/0  # Update Redis URL with password
      - CELERY_RESULT_BACKEND=redis://:EfeNgErMAnDIon@redis:6379/0
    volumes:
      - ./host_output_dir:/app/results  # Mount host directory to container's results dir
      - ./host_logging_dir:/app/logs    # Mount host directory to container's logs dir

  flower:
    build:
      context: ./worker
    container_name: flower
    command: celery -A tasks flower --basic_auth=admin:password123
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=redis://:EfeNgErMAnDIon@redis:6379/0  # Update Redis URL with password
      - CELERY_RESULT_BACKEND=redis://:EfeNgErMAnDIon@redis:6379/0
