services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]

  api:
    build:
      context: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - shared_storage:/app/uploads  # Shared volume for file exchange

  worker:
    build:
      context: ./worker
    mem_limit: 4g
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - shared_storage:/app/uploads  # Shared volume for file exchange
    deploy:
      replicas: 3  # Define 3 replicas for the worker to demonstrate scalability


  flower:
    build:
      context: ./worker
    container_name: flower
    entrypoint: []  # Override the entrypoint to disable entrypoint.sh (otherwise flower will run as a worker)
    command: celery -A celery_config flower --port=5555 --basic_auth=$FLOWER_BASIC_AUTH
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    env_file:
      - .env

volumes:
  shared_storage:
    driver: local
